### ISSUE TITLE
Can add the function of searching content in frames?

### ISSUE THREAD

**Issue by wantg** [brandon1024/find#380] opened 2022-05-05 13:45 UTC
when I search for a webpage that contains an iframe
matched highlight only effective with the top document
content in the iframe will be ignored

like https://pirate-bays.net/search?q=wire

**Comment by brandon1024** [comment] 2022-08-07 19:34
Closing as duplicate of https://github.com/brandon1024/find/issues/155

**Closed as completed by brandon1024** 2022-08-07 19:34 UTC
