### ISSUE TITLE
Invoke independently of toolbar icon

### ISSUE THREAD

**Issue by hejops** [brandon1024/find#324] opened 2020-08-08 13:13 UTC
AFAIK the search prompt only appears when the appropriate icon is in the toolbar. Can this behaviour be changed so that it can be used without the toolbar icon?

**Comment by hejops** [comment] 2020-09-03 17:41
I have assigned the keyboard shortcut, but the search prompt does not appear when the icon is not in the toolbar (Firefox).

**Comment by brandon1024** [comment] 2021-03-09 21:10
@hejops  This seems to work fine on my end. Can you retry?

**Comment by brandon1024** [comment] 2021-03-28 12:03
Closing this for now, since I can't reproduce the problem. If the problem persists, we can reopen this issue.

**Closed by brandon1024** 2021-03-28 12:03 UTC
