### ISSUE TITLE
Zero (0) results returned on www.coest.org

### ISSUE THREAD

**Issue by doychi** [brandon1024/find#386] opened 2022-09-07 02:09 UTC
## Issue Description
When visiting the CoEST website and using find+ in Chrome on Mac, 0 search result are returned

## Steps to Reproduce
-  go to www.coest.org
- open find+
- type in "want"

## Screenshots and Documentation
![2022-09-07_11-49-screenshot](https://user-images.githubusercontent.com/11004950/188772851-d5a0b092-50d9-49b8-9f48-08cc5f31f2ad.png)

**Comment by brandon1024** [comment] 2022-09-07 16:38
The reason this is happening is because the whole site is an iframe. Technical limitations of this extension prevent reading/manipulating the DOM of iframes. See further: https://github.com/brandon1024/find/issues/155

**Comment by brandon1024** [comment] 2022-10-07 12:26
Closing this as a duplicate of #155 .

**Closed as completed by brandon1024** 2022-10-07 12:26 UTC
