### ISSUE TITLE
[Feature request] Add option to disable omnibox

### ISSUE THREAD

**Issue by nerivera** [brandon1024/find#345] opened 2021-04-02 19:41 UTC
I often find myself searching for something starting with the word "find" in the address bar, only to have Find+ treat my search as a regex. This is incredibly annoying, and as I don't ever use the omnibox for regex searches (I always use the keyboard shortcut), I would like a way to disable it, but I couldn't find an option on Find+ or on my browser. Please add this option.

**Comment by brandon1024** [comment] 2021-04-03 01:15
Thanks for your interest @nerivera. This is a duplicate of https://github.com/brandon1024/find/issues/312, which was closed because there's not really much I can do. Here's my reasoning from that ticket:

> I looked into this in a while back when another user asked a similar question, and determined that it is not possible to disable the Omnibox integration programatically.
> 
> One option is to change the omnibox keyword for the extension to "find-ext", or similar, but there are a lot of users that use the Omnibox feature and it would be confusing to them if the keyword changed. If enough users want this change, then I'll implement it, but for now I'm going to keep the existing functionality.
>
> The extension omnibox features are defined through the extension's manifest file, which is static and can't be modified programmatically. This is what prevents me from modifying the omnibox behavior.

Perhaps in a later version we'll rename the keyword if we get more requests for this, but for now it'll stay the same.

**Closed by brandon1024** 2021-04-03 01:15 UTC

**Comment by nerivera** [comment] 2021-04-21 20:16
Here's an idea: make two different versions of the extension on two different branches, one with omnibox, and one without. Since this might be confusing for people searching for the extension on the Chrome Web Store or Firefox Add-ons, you could release the branch with omnibox on the extension stores and provide the branch without omnibox on GitHub for users to install manually, maybe with a wiki page linked from the README to go with it explaining how to install it. Or, if you're okay with having two different versions of the extension on the extension stores, just release both and explain the difference in the descriptions.

**Comment by brandon1024** [comment] 2021-04-22 11:29
To be completely honest, I'm not interested in doing that for a number of reasons. Managing extensions in the store takes time. Deploying the extension to the Chrome Web Store and the Firefox add-ons store takes time. What you propose would mean that I would need to maintain four extensions, instead of two. That means that there are four sources of feedback as well, and it makes it harder to track the analytics of the extension usage. Additionally, as changes are introduced into the development branch I have to integrate them into two branches at release time. All of this means more effort on my part, which isn't compelling to do when a very small subset (two or three out of nearly ten thousand active users) want this feature.

If you're really interested in removing the omnibox functionality, you can simply clone this repository locally, update the manifest, and then install the extension yourself.

**Comment by Kaminate** [comment] 2023-08-28 02:11
> If you're really interested in removing the omnibox functionality, you can simply clone this repository locally, update the manifest, and then install the extension yourself.

My steps to do this if anyone else wants to try: https://github.com/Kaminate/find-no-omnibox

**Comment by mcgwiz** [comment] 2023-08-31 22:24
Feel free to use this, which was built from [79e3acb7cc0bba62d45c0cbb9ba9cafc5a208da5](https://github.com/brandon1024/find/tree/79e3acb7cc0bba62d45c0cbb9ba9cafc5a208da5) with the single change of adding a `+` to the omnibox keyword: https://notes.mcgwiz.com/assets/attachments/66e7ce7c1c3d41488a5d-2.2.3.xpi
